-- Drop table

-- DROP TABLE public.architectural_styles;

CREATE TABLE public.architectural_styles (
                                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             description varchar(10000) NULL,
                                             description_en varchar(255) NULL,
                                             CONSTRAINT architectural_styles_pkey PRIMARY KEY (id)
);


-- public.bibliography definition

-- Drop table

-- DROP TABLE public.bibliography;

CREATE TABLE public.bibliography (
                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     source_type varchar(20) NOT NULL,
                                     external_id text NULL,
                                     doi text NULL,
                                     isbn text NULL,
                                     title text NOT NULL,
                                     authors text NULL,
                                     "year" int4 NULL,
                                     container_title text NULL,
                                     publisher text NULL,
                                     volume text NULL,
                                     issue text NULL,
                                     pages text NULL,
                                     url text NULL,
                                     csl jsonb NULL,
                                     raw_source jsonb NULL,
                                     created_at timestamp DEFAULT now() NOT NULL,
                                     updated_at timestamp DEFAULT now() NOT NULL,
                                     CONSTRAINT pk_bibliography PRIMARY KEY (id)
);


-- public.country definition

-- Drop table

-- DROP TABLE public.country;

CREATE TABLE public.country (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                description text NULL,
                                description_en varchar(255) NULL,
                                country_code varchar(5) NULL,
                                is_core_country bool DEFAULT false NULL,
                                CONSTRAINT country_pkey PRIMARY KEY (id)
);



-- public.diocese definition

-- Drop table

-- DROP TABLE public.diocese;

CREATE TABLE public.diocese (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                description varchar(255) NULL,
                                description_en varchar(255) NULL,
                                CONSTRAINT diocese_pkey PRIMARY KEY (id)
);


-- public.event_types definition

-- Drop table

-- DROP TABLE public.event_types;

CREATE TABLE public.event_types (
                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    "name" varchar(255) NULL,
                                    description varchar(10000) NULL,
                                    description_en varchar(1000) NULL,
                                    CONSTRAINT event_type_pk PRIMARY KEY (id)
);


-- public.feature_types definition

-- Drop table

-- DROP TABLE public.feature_types;

CREATE TABLE public.feature_types (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      "type" varchar(255) NULL,
                                      description varchar(10000) NULL,
                                      description_en varchar(1000) NULL,
                                      CONSTRAINT feature_type_pk PRIMARY KEY (id)
);


-- public.file_blob definition

-- Drop table

-- DROP TABLE public.file_blob;

CREATE TABLE public.file_blob (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  "path" text NOT NULL,
                                  mime text NULL,
                                  "size" int8 NULL,
                                  created_at timestamp DEFAULT now() NOT NULL,
                                  CONSTRAINT file_blob_pkey PRIMARY KEY (id)
);


-- public.historical_period definition

-- Drop table

-- DROP TABLE public.historical_period;

CREATE TABLE public.historical_period (
                                          id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                          description varchar(255) NULL,
                                          description_en varchar(255) NULL,
                                          CONSTRAINT historical_period_description_key UNIQUE (description),
                                          CONSTRAINT historical_period_pkey PRIMARY KEY (id),
                                          CONSTRAINT uk_historical_period_description_en UNIQUE (description_en)
);


-- public.materials definition

-- Drop table

-- DROP TABLE public.materials;

CREATE TABLE public.materials (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  "name" varchar(255) NULL,
                                  description varchar(10000) NULL,
                                  materials_type varchar(255) NULL,
                                  description_en varchar(1000) NULL,
                                  CONSTRAINT materials_pk PRIMARY KEY (id)
);


-- public.media_types definition

-- Drop table

-- DROP TABLE public.media_types;

CREATE TABLE public.media_types (
                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    "type" varchar(255) NOT NULL,
                                    description varchar(10000) NULL,
                                    description_en varchar(1000) NULL,
                                    CONSTRAINT media_type_pk PRIMARY KEY (id)
);


-- public.ownership_type definition

-- Drop table

-- DROP TABLE public.ownership_type;

CREATE TABLE public.ownership_type (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       description varchar(255) NULL,
                                       description_en varchar(255) NULL,
                                       CONSTRAINT ownership_type_description_key UNIQUE (description),
                                       CONSTRAINT ownership_type_pkey PRIMARY KEY (id)
);


-- public.phase_material definition

-- Drop table

-- DROP TABLE public.phase_material;

CREATE TABLE public.phase_material (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       description varchar(255) NULL,
                                       description_en varchar(255) NULL,
                                       CONSTRAINT phase_material_description_key UNIQUE (description),
                                       CONSTRAINT phase_material_pkey PRIMARY KEY (id)
);


-- public.phase_technique definition

-- Drop table

-- DROP TABLE public.phase_technique;

CREATE TABLE public.phase_technique (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        description varchar(255) NULL,
                                        description_en varchar(255) NULL,
                                        CONSTRAINT phase_technique_description_key UNIQUE (description),
                                        CONSTRAINT phase_technique_pkey PRIMARY KEY (id)
);


-- public.region definition

-- Drop table

-- DROP TABLE public.region;

CREATE TABLE public.region (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               description varchar(255) NULL,
                               description_en varchar(255) NULL,
                               CONSTRAINT pk_region PRIMARY KEY (id),
                               CONSTRAINT uk_region_description UNIQUE (description),
                               CONSTRAINT uk_region_description_en UNIQUE (description_en)
);


-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              role_type varchar(50) NOT NULL,
                              CONSTRAINT roles_pkey PRIMARY KEY (id),
                              CONSTRAINT roles_role_type_key UNIQUE (role_type)
);


-- public.structure_types definition

-- Drop table

-- DROP TABLE public.structure_types;

CREATE TABLE public.structure_types (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        description varchar(10000) NULL,
                                        description_en varchar(1000) NULL,
                                        CONSTRAINT structure_type_pk PRIMARY KEY (id)
);


-- public.use_of_building definition

-- Drop table

-- DROP TABLE public.use_of_building;

CREATE TABLE public.use_of_building (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        building_use varchar(32) NULL,
                                        religious_type varchar(32) NULL,
                                        fortification_type varchar(32) NULL,
                                        specific_notes text NULL,
                                        CONSTRAINT use_of_building_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              username varchar(255) NOT NULL,
                              email varchar(255) NOT NULL,
                              password_hash varchar(5000) NOT NULL,
                              full_name varchar(255) NOT NULL,
                              institution varchar(150) NULL,
                              is_active bool DEFAULT true NULL,
                              last_login timestamp DEFAULT CURRENT_TIMESTAMP NULL,
                              created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              CONSTRAINT users_email_key UNIQUE (email),
                              CONSTRAINT users_pk PRIMARY KEY (id),
                              CONSTRAINT users_username_key UNIQUE (username)
);


-- public.contributors definition

-- Drop table

-- DROP TABLE public.contributors;

CREATE TABLE public.contributors (
                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     architect_builder varchar(255) NULL,
                                     patron varchar(255) NULL,
                                     researcher_user_id int8 NULL,
                                     CONSTRAINT contributors_pkey PRIMARY KEY (id),
                                     CONSTRAINT fk_contributors_researcher_user FOREIGN KEY (researcher_user_id) REFERENCES public.users(id) ON DELETE SET NULL
);
CREATE INDEX idx_contributors_researcher ON public.contributors USING btree (researcher_user_id);


-- public.dating definition

-- Drop table

-- DROP TABLE public.dating;

CREATE TABLE public.dating (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               historical_period_id int8 NULL,
                               dating_start varchar(100) NULL,
                               dating_end varchar(100) NULL,
                               dating_type varchar(50) NULL,
                               significant_historical_events varchar(1000) NULL,
                               CONSTRAINT dating_pkey PRIMARY KEY (id),
                               CONSTRAINT fk_dating_historical_period FOREIGN KEY (historical_period_id) REFERENCES public.historical_period(id) ON DELETE RESTRICT
);
CREATE INDEX idx_dating_historical_period_id ON public.dating USING btree (historical_period_id);


-- public.media_type_file_format definition

-- Drop table

-- DROP TABLE public.media_type_file_format;

CREATE TABLE public.media_type_file_format (
                                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                               media_type_id int8 NOT NULL,
                                               file_format varchar(255) NOT NULL,
                                               CONSTRAINT media_type_file_format_pkey PRIMARY KEY (id),
                                               CONSTRAINT fk_media_type_file_format_media_types FOREIGN KEY (media_type_id) REFERENCES public.media_types(id) ON DELETE CASCADE
);


-- public.ownership definition

-- Drop table

-- DROP TABLE public.ownership;

CREATE TABLE public.ownership (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  ownership_type_id int8 NULL,
                                  specific_clarification varchar(1000) NULL,
                                  owner_entity_name varchar(255) NULL,
                                  cadastral_reference varchar(255) NULL,
                                  address varchar(255) NULL,
                                  zip_code varchar(20) NULL,
                                  building_reference varchar(50) NULL,
                                  use_of_building_id int8 NULL,
                                  religious_usage varchar(50) NULL,
                                  fortification_project varchar(50) NULL,
                                  building_reference_number text NULL,
                                  CONSTRAINT ownership_pkey PRIMARY KEY (id),
                                  CONSTRAINT fk_ownership_ownership_type FOREIGN KEY (ownership_type_id) REFERENCES public.ownership_type(id) ON DELETE RESTRICT,
                                  CONSTRAINT fk_ownership_use_of_building FOREIGN KEY (use_of_building_id) REFERENCES public.use_of_building(id) ON DELETE RESTRICT
);
CREATE INDEX idx_ownership_type ON public.ownership USING btree (ownership_type_id);
CREATE INDEX idx_ownership_uob ON public.ownership USING btree (use_of_building_id);


-- public.regional_unit definition

-- Drop table

-- DROP TABLE public.regional_unit;

CREATE TABLE public.regional_unit (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      description varchar(255) NULL,
                                      region_id int8 NULL,
                                      description_en varchar(255) NULL,
                                      CONSTRAINT regional_unit_pkey PRIMARY KEY (id),
                                      CONSTRAINT uq_regional_unit_description UNIQUE (description),
                                      CONSTRAINT uq_regional_unit_description_en UNIQUE (description_en),
                                      CONSTRAINT fk_regional_unit_region FOREIGN KEY (region_id) REFERENCES public.region(id)
);
CREATE INDEX idx_regional_unit_region_id ON public.regional_unit USING btree (region_id);
CREATE INDEX idx_ru_descr_trgm ON public.regional_unit USING gin (lower((description)::text) gin_trgm_ops);


-- public.unit definition

-- Drop table

-- DROP TABLE public.unit;

CREATE TABLE public.unit (
                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                             description text NULL,
                             country_id int8 NULL,
                             description_en varchar(255) NULL,
                             CONSTRAINT unit_pkey PRIMARY KEY (id),
                             CONSTRAINT fk_unit_country FOREIGN KEY (country_id) REFERENCES public.country(id) ON DELETE RESTRICT
);


-- public.user_roles definition

-- Drop table

-- DROP TABLE public.user_roles;

CREATE TABLE public.user_roles (
                                   user_id int8 NOT NULL,
                                   role_id int8 NOT NULL,
                                   CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
                                   CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE,
                                   CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);


-- public.greek_administrative_division definition

-- Drop table

-- DROP TABLE public.greek_administrative_division;

CREATE TABLE public.greek_administrative_division (
                                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                      regional_unit_id int8 NULL,
                                                      created_at timestamptz DEFAULT now() NULL,
                                                      updated_at timestamptz DEFAULT now() NULL,
                                                      province text NULL,
                                                      local_community text NULL,
                                                      municipality_text varchar(255) NULL,
                                                      CONSTRAINT pk_greek_administrative_division PRIMARY KEY (id),
                                                      CONSTRAINT fk_gad_regional_unit FOREIGN KEY (regional_unit_id) REFERENCES public.regional_unit(id) ON DELETE RESTRICT
);
CREATE INDEX idx_gad_ru ON public.greek_administrative_division USING btree (regional_unit_id);


-- public.greek_prefecture definition

-- Drop table

-- DROP TABLE public.greek_prefecture;

CREATE TABLE public.greek_prefecture (
                                         id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                         description varchar(255) NULL,
                                         description_en varchar(255) NULL,
                                         unit_id int8 NULL,
                                         CONSTRAINT greek_prefecture_pkey PRIMARY KEY (id),
                                         CONSTRAINT fk_greek_prefecture_unit FOREIGN KEY (unit_id) REFERENCES public.unit(id) ON DELETE RESTRICT
);


-- public.greek_prefecture_subdivision definition

-- Drop table

-- DROP TABLE public.greek_prefecture_subdivision;

CREATE TABLE public.greek_prefecture_subdivision (
                                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                     description varchar(255) NULL,
                                                     description_en varchar(255) NULL,
                                                     greek_prefecture_id int8 NULL,
                                                     CONSTRAINT greek_prefecture_subdivision_pkey PRIMARY KEY (id),
                                                     CONSTRAINT fk_greek_prefecture_subdivision_prefecture FOREIGN KEY (greek_prefecture_id) REFERENCES public.greek_prefecture(id) ON DELETE RESTRICT
);


-- public.locations definition

-- Drop table

-- DROP TABLE public.locations;

CREATE TABLE public.locations (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  latitude numeric(9, 6) NULL,
                                  longitude numeric(9, 6) NULL,
                                  elevation int4 NULL,
                                  address text NULL,
                                  zip_code text NULL,
                                  settlement_notes text NULL,
                                  place_name_notes text NULL,
                                  regional_geographic_unit_id int8 NULL,
                                  greek_prefecture_id int8 NULL,
                                  prefecture_subdivision_id int8 NULL,
                                  regional_geographic_unit text NULL,
                                  country_id int8 NULL,
                                  coordinates varchar(64) NULL,
                                  CONSTRAINT locations_pkey PRIMARY KEY (id),
                                  CONSTRAINT fk_locations_country FOREIGN KEY (country_id) REFERENCES public.country(id) ON DELETE RESTRICT,
                                  CONSTRAINT fk_locations_greek_prefecture FOREIGN KEY (greek_prefecture_id) REFERENCES public.greek_prefecture(id) ON DELETE RESTRICT,
                                  CONSTRAINT fk_locations_pref_subdivision FOREIGN KEY (prefecture_subdivision_id) REFERENCES public.greek_prefecture_subdivision(id) ON DELETE RESTRICT,
                                  CONSTRAINT fk_locations_regional_geographic_unit FOREIGN KEY (regional_geographic_unit_id) REFERENCES public.unit(id) ON DELETE RESTRICT
);
CREATE INDEX idx_locations_address_fuc_trgm ON public.locations USING gin (f_unaccent_ci(address) gin_trgm_ops);
CREATE INDEX idx_locations_address_lower_trgm ON public.locations USING gin (lower(address) gin_trgm_ops);
CREATE INDEX idx_locations_country ON public.locations USING btree (country_id);
CREATE INDEX idx_locations_greek_prefecture ON public.locations USING btree (greek_prefecture_id);
CREATE INDEX idx_locations_pref_subdivision ON public.locations USING btree (prefecture_subdivision_id);
CREATE INDEX idx_locations_regional_geographic_unit ON public.locations USING btree (regional_geographic_unit_id);
CREATE INDEX idx_locations_unit ON public.locations USING btree (regional_geographic_unit_id);
CREATE INDEX idx_locations_zip_fuc_trgm ON public.locations USING gin (f_unaccent_ci(zip_code) gin_trgm_ops);
CREATE INDEX idx_locations_zip_lower_trgm ON public.locations USING gin (lower(zip_code) gin_trgm_ops);


-- public.buildings_monuments definition

-- Drop table

-- DROP TABLE public.buildings_monuments;

CREATE TABLE public.buildings_monuments (
                                            id uuid NOT NULL,
                                            "name" varchar(255) NULL,
                                            original_name varchar(255) NULL,
                                            structure_type_id int8 NULL,
                                            construction_year_start date NULL,
                                            construction_year_end date NULL,
                                            preservation_status varchar(255) NULL,
                                            description text NULL,
                                            historical_significance text NULL,
                                            image bytea NULL,
                                            image_content_type varchar(255) NULL,
                                            period_start varchar(100) NULL,
                                            period_end varchar(100) NULL,
                                            location_id int8 NULL,
                                            diocese_id int8 NULL,
                                            religious_division varchar(255) NULL,
                                            created_at timestamp NULL,
                                            updated_at timestamp NULL,
                                            created_by int8 NULL,
                                            image_url text NULL,
                                            ownership_id int8 NULL,
                                            dating_id int8 NULL,
                                            contributors_id int8 NULL,
                                            legal_status varchar(50) NULL,
                                            other_special_protection text NULL,
                                            greek_administrative_division_id int8 NULL,
                                            description_en varchar(255) NULL,
                                            site text NULL,
                                            administrative_division text NULL,
                                            region_division text NULL,
                                            municipality_division text NULL,
                                            building_reference text NULL,
                                            state_of_conservation varchar(50) NULL,
                                            building_materials text NULL,
                                            CONSTRAINT buildings_monuments_pkey PRIMARY KEY (id),
                                            CONSTRAINT fk_bm_contributors FOREIGN KEY (contributors_id) REFERENCES public.contributors(id) ON DELETE SET NULL,
                                            CONSTRAINT fk_bm_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
                                            CONSTRAINT fk_bm_dating FOREIGN KEY (dating_id) REFERENCES public.dating(id) ON DELETE SET NULL,
                                            CONSTRAINT fk_bm_ownership FOREIGN KEY (ownership_id) REFERENCES public.ownership(id) ON DELETE RESTRICT,
                                            CONSTRAINT fk_bm_structure_type FOREIGN KEY (structure_type_id) REFERENCES public.structure_types(id) ON DELETE RESTRICT,
                                            CONSTRAINT fk_buildings_monuments_diocese FOREIGN KEY (diocese_id) REFERENCES public.diocese(id) ON DELETE RESTRICT,
                                            CONSTRAINT fk_buildings_monuments_gad FOREIGN KEY (greek_administrative_division_id) REFERENCES public.greek_administrative_division(id) ON DELETE SET NULL,
                                            CONSTRAINT fk_buildings_monuments_location_id FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE RESTRICT
);
CREATE INDEX idx_bm_contributors_id ON public.buildings_monuments USING btree (contributors_id);
CREATE INDEX idx_bm_dating_id ON public.buildings_monuments USING btree (dating_id);
CREATE INDEX idx_bm_ownership_id ON public.buildings_monuments USING btree (ownership_id);


-- public.conservation_intervention definition

-- Drop table

-- DROP TABLE public.conservation_intervention;

CREATE TABLE public.conservation_intervention (
                                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                  monument_id uuid NULL,
                                                  intervention_description varchar(5000) NULL,
                                                  date_from varchar(50) NULL,
                                                  date_to varchar(50) NULL,
                                                  responsible_authority varchar(500) NULL,
                                                  collaborators varchar(5000) NULL,
                                                  digital_assets_notes varchar(2000) NULL,
                                                  photos jsonb DEFAULT '[]'::jsonb NULL,
                                                  assets jsonb DEFAULT '[]'::jsonb NULL,
                                                  CONSTRAINT conservation_intervention_pkey PRIMARY KEY (id),
                                                  CONSTRAINT fk_conserv_interv_monument FOREIGN KEY (monument_id) REFERENCES public.buildings_monuments(id) ON DELETE CASCADE
);
CREATE INDEX idx_conserv_interv_monument ON public.conservation_intervention USING btree (monument_id);


-- public.constructional_phase definition

-- Drop table

-- DROP TABLE public.constructional_phase;

CREATE TABLE public.constructional_phase (
                                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             monument_id uuid NULL,
                                             phase_type varchar(50) NULL,
                                             phase_description varchar(1000) NULL,
                                             phase_use_notes varchar(5000) NULL,
                                             state_of_conservation varchar(50) NULL,
                                             conservation_notes varchar(5000) NULL,
                                             phase_dating_start varchar(50) NULL,
                                             phase_dating_end varchar(50) NULL,
                                             use_in_phase varchar(32) NULL,
                                             phase_description_en varchar(1000) NULL,
                                             phase_material text NULL,
                                             phase_technique text NULL,
                                             CONSTRAINT constructional_phase_pkey PRIMARY KEY (id),
                                             CONSTRAINT fk_constructional_phase_monument_id FOREIGN KEY (monument_id) REFERENCES public.buildings_monuments(id) ON DELETE CASCADE
);
CREATE INDEX idx_phase_monument ON public.constructional_phase USING btree (monument_id);


-- public.constructional_phase_arch_style definition

-- Drop table

-- DROP TABLE public.constructional_phase_arch_style;

CREATE TABLE public.constructional_phase_arch_style (
                                                        phase_id int8 NOT NULL,
                                                        architectural_style_id int8 NOT NULL,
                                                        CONSTRAINT pk_phase_arch_style PRIMARY KEY (phase_id, architectural_style_id),
                                                        CONSTRAINT fk_phase_arch_style_phase FOREIGN KEY (phase_id) REFERENCES public.constructional_phase(id) ON DELETE CASCADE,
                                                        CONSTRAINT fk_phase_arch_style_style FOREIGN KEY (architectural_style_id) REFERENCES public.architectural_styles(id) ON DELETE RESTRICT
);
CREATE INDEX idx_phase_arch_style_phase ON public.constructional_phase_arch_style USING btree (phase_id);
CREATE INDEX idx_phase_arch_style_style ON public.constructional_phase_arch_style USING btree (architectural_style_id);


-- public.constructional_phase_material definition

-- Drop table

-- DROP TABLE public.constructional_phase_material;

CREATE TABLE public.constructional_phase_material (
                                                      phase_id int8 NOT NULL,
                                                      material_id int8 NOT NULL,
                                                      CONSTRAINT pk_phase_material PRIMARY KEY (phase_id, material_id),
                                                      CONSTRAINT fk_phase_material_material FOREIGN KEY (material_id) REFERENCES public.phase_material(id) ON DELETE RESTRICT,
                                                      CONSTRAINT fk_phase_material_phase FOREIGN KEY (phase_id) REFERENCES public.constructional_phase(id) ON DELETE CASCADE
);
CREATE INDEX idx_phase_material_material ON public.constructional_phase_material USING btree (material_id);
CREATE INDEX idx_phase_material_phase ON public.constructional_phase_material USING btree (phase_id);


-- public.constructional_phase_technique definition

-- Drop table

-- DROP TABLE public.constructional_phase_technique;

CREATE TABLE public.constructional_phase_technique (
                                                       phase_id int8 NOT NULL,
                                                       technique_id int8 NOT NULL,
                                                       CONSTRAINT pk_phase_technique PRIMARY KEY (phase_id, technique_id),
                                                       CONSTRAINT fk_phase_technique_phase FOREIGN KEY (phase_id) REFERENCES public.constructional_phase(id) ON DELETE CASCADE,
                                                       CONSTRAINT fk_phase_technique_technique FOREIGN KEY (technique_id) REFERENCES public.phase_technique(id) ON DELETE RESTRICT
);
CREATE INDEX idx_phase_technique_phase ON public.constructional_phase_technique USING btree (phase_id);
CREATE INDEX idx_phase_technique_tech ON public.constructional_phase_technique USING btree (technique_id);


-- public.digital_asset definition

-- Drop table

-- DROP TABLE public.digital_asset;

CREATE TABLE public.digital_asset (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      monument_id uuid NOT NULL,
                                      category varchar(32) NOT NULL,
                                      drawing_type varchar(32) NULL,
                                      file_url text NULL,
                                      file_mime_type text NULL,
                                      thumbnail_url text NULL,
                                      caption text NULL,
                                      "source" text NULL,
                                      copyright_license text NULL,
                                      creator_name text NULL,
                                      taken_or_date date NULL,
                                      embed_url text NULL,
                                      width_px int4 NULL,
                                      height_px int4 NULL,
                                      created_at timestamp DEFAULT LOCALTIMESTAMP NOT NULL,
                                      updated_at timestamp DEFAULT LOCALTIMESTAMP NOT NULL,
                                      file_blob_id int8 NOT NULL,
                                      conservation_intervention_id int8 NULL,
                                      CONSTRAINT ck_da_category CHECK (((category)::text = ANY ((ARRAY['PHOTOGRAPH'::character varying, 'DRAWING'::character varying, 'OTHER'::character varying])::text[]))),
	CONSTRAINT ck_da_drawing_type_values CHECK (((drawing_type IS NULL) OR ((drawing_type)::text = ANY ((ARRAY['PLAN'::character varying, 'SECTION'::character varying, 'ELEVATION'::character varying, 'OTHER'::character varying])::text[])))),
	CONSTRAINT ck_da_drawing_type_when_drawing CHECK (((drawing_type IS NULL) OR ((category)::text = 'DRAWING'::text))),
	CONSTRAINT digital_asset_pkey PRIMARY KEY (id),
	CONSTRAINT fk_digital_asset_buildings_monuments FOREIGN KEY (monument_id) REFERENCES public.buildings_monuments(id) ON DELETE CASCADE,
	CONSTRAINT fk_digital_asset_conservation_intervention FOREIGN KEY (conservation_intervention_id) REFERENCES public.conservation_intervention(id) ON DELETE CASCADE,
	CONSTRAINT fk_digital_asset_file_blob FOREIGN KEY (file_blob_id) REFERENCES public.file_blob(id) ON DELETE RESTRICT
);
CREATE INDEX idx_da_conservation_intervention_id ON public.digital_asset USING btree (conservation_intervention_id);
CREATE INDEX idx_da_file_blob_id ON public.digital_asset USING btree (file_blob_id);
CREATE INDEX idx_da_mon_cat ON public.digital_asset USING btree (monument_id, category);
CREATE INDEX idx_da_mon_created ON public.digital_asset USING btree (monument_id, created_at DESC);
CREATE INDEX idx_da_mon_mime_lower ON public.digital_asset USING btree (monument_id, lower(file_mime_type));
CREATE INDEX idx_da_mon_taken ON public.digital_asset USING btree (monument_id, taken_or_date DESC);
CREATE INDEX idx_da_monument ON public.digital_asset USING btree (monument_id);
CREATE INDEX idx_da_monument_conservation_intervention ON public.digital_asset USING btree (monument_id, conservation_intervention_id);


-- public.historical_events definition

-- Drop table

-- DROP TABLE public.historical_events;

CREATE TABLE public.historical_events (
                                          id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                          structure_id uuid NULL,
                                          event_type_id int8 NULL,
                                          date_start date NULL,
                                          date_end date NULL,
                                          description text NULL,
                                          historical_figures jsonb NULL,
                                          significance text NULL,
                                          description_en text NULL,
                                          CONSTRAINT historical_events_pkey PRIMARY KEY (id),
                                          CONSTRAINT fk_hist_event_structure FOREIGN KEY (structure_id) REFERENCES public.buildings_monuments(id),
                                          CONSTRAINT fk_hist_event_type FOREIGN KEY (event_type_id) REFERENCES public.event_types(id)
);


-- public.inspection_appointment definition

-- Drop table

-- DROP TABLE public.inspection_appointment;

CREATE TABLE public.inspection_appointment (
                                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                               monument_id uuid NOT NULL,
                                               visitor_name varchar(255) NOT NULL,
                                               visitor_email varchar(255) NULL,
                                               contact_info varchar(255) NULL,
                                               notes text NULL,
                                               status varchar(16) DEFAULT 'ACTIVE'::character varying NULL,
                                               created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
                                               updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
                                               scheduled_date date NOT NULL,
                                               time_start time NOT NULL,
                                               time_end time NOT NULL,
                                               user_id int8 NOT NULL,
                                               CONSTRAINT ck_ia_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'POSTPONED'::character varying])::text[]))),
	CONSTRAINT ck_ia_time_window CHECK ((time_start <= time_end)),
	CONSTRAINT ck_ia_times_whole_minute CHECK (((date_trunc('minute'::text, (time_start)::interval) = (time_start)::interval) AND (date_trunc('minute'::text, (time_end)::interval) = (time_end)::interval))),
	CONSTRAINT inspection_appointment_pkey PRIMARY KEY (id),
	CONSTRAINT fk_ia_buildings_monuments FOREIGN KEY (monument_id) REFERENCES public.buildings_monuments(id) ON DELETE CASCADE,
	CONSTRAINT fk_inspection_appointment_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_ia_active_date ON public.inspection_appointment USING btree (scheduled_date) WHERE ((status)::text = 'ACTIVE'::text);
CREATE INDEX idx_ia_mon_status_date_start ON public.inspection_appointment USING btree (monument_id, status, scheduled_date, time_start, time_end);
CREATE INDEX idx_ia_monument ON public.inspection_appointment USING btree (monument_id);
CREATE INDEX idx_ia_scheduled_date ON public.inspection_appointment USING btree (scheduled_date);
CREATE INDEX idx_ia_status_date_start ON public.inspection_appointment USING btree (status, scheduled_date, time_start, time_end);
CREATE INDEX idx_visit_monument_date ON public.inspection_appointment USING btree (monument_id, scheduled_date);
CREATE INDEX idx_visit_status ON public.inspection_appointment USING btree (status);
CREATE INDEX idx_visit_user ON public.inspection_appointment USING btree (user_id);
CREATE INDEX idx_visit_user_date ON public.inspection_appointment USING btree (user_id, scheduled_date);
CREATE UNIQUE INDEX uq_ia_user_monument_date_time_start ON public.inspection_appointment USING btree (user_id, monument_id, scheduled_date, time_start) WHERE ((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('PENDING'::character varying)::text, ('CONFIRMED'::character varying)::text]));


-- public.monument_bibliography definition

-- Drop table

-- DROP TABLE public.monument_bibliography;

CREATE TABLE public.monument_bibliography (
                                              monument_id uuid NOT NULL,
                                              bibliography_id int8 NOT NULL,
                                              "position" int4 NULL,
                                              note text NULL,
                                              CONSTRAINT pk_monument_bibliography PRIMARY KEY (monument_id, bibliography_id),
                                              CONSTRAINT fk_mb_bibliography FOREIGN KEY (bibliography_id) REFERENCES public.bibliography(id) ON DELETE CASCADE,
                                              CONSTRAINT fk_mb_monument FOREIGN KEY (monument_id) REFERENCES public.buildings_monuments(id) ON DELETE CASCADE
);
CREATE INDEX idx_mb_bibliography ON public.monument_bibliography USING btree (bibliography_id);
CREATE INDEX idx_mb_monument ON public.monument_bibliography USING btree (monument_id);


-- public.related_structures definition

-- Drop table

-- DROP TABLE public.related_structures;

CREATE TABLE public.related_structures (
                                           id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                           structure_id_1 uuid NULL,
                                           structure_id_2 uuid NULL,
                                           relationship_type varchar(255) NULL,
                                           description varchar(10000) NULL,
                                           description_en varchar(1000) NULL,
                                           CONSTRAINT related_structures_pk PRIMARY KEY (id),
                                           CONSTRAINT fk_structure1 FOREIGN KEY (structure_id_1) REFERENCES public.buildings_monuments(id),
                                           CONSTRAINT fk_structure2 FOREIGN KEY (structure_id_2) REFERENCES public.buildings_monuments(id)
);


-- public.architectural_features definition

-- Drop table

-- DROP TABLE public.architectural_features;

CREATE TABLE public.architectural_features (
                                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                               structure_id uuid NULL,
                                               feature_type_id int8 NULL,
                                               "name" varchar(255) NULL,
                                               description text NULL,
                                               construction_period varchar(255) NULL,
                                               material_id int8 NULL,
                                               dimensions jsonb NULL,
                                               description_en varchar(255) NULL,
                                               CONSTRAINT architectural_features_pkey PRIMARY KEY (id),
                                               CONSTRAINT fk_af_feature_type FOREIGN KEY (feature_type_id) REFERENCES public.feature_types(id),
                                               CONSTRAINT fk_af_material FOREIGN KEY (material_id) REFERENCES public.materials(id),
                                               CONSTRAINT fk_af_structure FOREIGN KEY (structure_id) REFERENCES public.buildings_monuments(id)
);


-- public.building_monument_architectural_style definition

-- Drop table

-- DROP TABLE public.building_monument_architectural_style;

CREATE TABLE public.building_monument_architectural_style (
                                                              building_monument_id uuid NOT NULL,
                                                              architectural_style_id int8 NOT NULL,
                                                              CONSTRAINT pk_bm_architectural_style PRIMARY KEY (building_monument_id, architectural_style_id),
                                                              CONSTRAINT fk_bm_arch_style_bm FOREIGN KEY (building_monument_id) REFERENCES public.buildings_monuments(id) ON DELETE CASCADE,
                                                              CONSTRAINT fk_bm_arch_style_style FOREIGN KEY (architectural_style_id) REFERENCES public.architectural_styles(id) ON DELETE RESTRICT
);


-- public.media definition

-- Drop table

-- DROP TABLE public.media;

CREATE TABLE public.media (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              structure_id uuid NULL,
                              feature_id int8 NULL,
                              media_type_id int8 NULL,
                              title varchar(255) NULL,
                              file_path varchar(1024) NULL,
                              storage_location varchar(1024) NULL,
                              caption text NULL,
                              credit varchar(255) NULL,
                              creation_date date NULL,
                              upload_date timestamp DEFAULT now() NULL,
                              is_primary bool DEFAULT false NULL,
                              metadata jsonb NULL,
                              CONSTRAINT media_pkey PRIMARY KEY (id),
                              CONSTRAINT fk_media_feature FOREIGN KEY (feature_id) REFERENCES public.architectural_features(id),
                              CONSTRAINT fk_media_structure FOREIGN KEY (structure_id) REFERENCES public.buildings_monuments(id),
                              CONSTRAINT fk_media_type FOREIGN KEY (media_type_id) REFERENCES public.media_types(id)
);

-- Index expression / partial index test block

CREATE TABLE public.index_expression_test (
                                              id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                              name_english varchar(255) NULL,
                                              name_greek varchar(255) NULL,
                                              email varchar(255) NULL,
                                              status varchar(50) NULL,
                                              category varchar(100) NULL,
                                              created_at timestamp DEFAULT now() NOT NULL,
                                              updated_at timestamp DEFAULT now() NOT NULL,
                                              deleted_at timestamp NULL,
                                              mime_type text NULL,
                                              description text NULL,
                                              zip_code text NULL,
                                              address text NULL,
                                              CONSTRAINT index_expression_test_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_iet_name_english_lower
    ON public.index_expression_test USING btree (lower((name_english)::text));

CREATE INDEX idx_iet_name_greek_lower
    ON public.index_expression_test USING btree (lower((name_greek)::text));

CREATE INDEX idx_iet_email_lower_unique_test
    ON public.index_expression_test USING btree (lower((email)::text));

CREATE INDEX idx_iet_created_desc
    ON public.index_expression_test USING btree (created_at DESC);

CREATE INDEX idx_iet_updated_asc
    ON public.index_expression_test USING btree (updated_at ASC);

CREATE INDEX idx_iet_status_created_desc
    ON public.index_expression_test USING btree (status, created_at DESC);

CREATE INDEX idx_iet_category_status_created
    ON public.index_expression_test USING btree (category, status, created_at DESC);

CREATE INDEX idx_iet_mime_lower
    ON public.index_expression_test USING btree (lower(mime_type));

CREATE INDEX idx_iet_description_lower_trgm
    ON public.index_expression_test USING gin (lower(description) gin_trgm_ops);

CREATE INDEX idx_iet_address_fuc_trgm
    ON public.index_expression_test USING gin (f_unaccent_ci(address) gin_trgm_ops);

CREATE INDEX idx_iet_zip_lower_trgm
    ON public.index_expression_test USING gin (lower(zip_code) gin_trgm_ops);

CREATE INDEX idx_iet_active_status
    ON public.index_expression_test USING btree (status)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_iet_active_created
    ON public.index_expression_test USING btree (created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_iet_confirmed_created
    ON public.index_expression_test USING btree (created_at DESC)
    WHERE ((status)::text = 'CONFIRMED'::text);

CREATE UNIQUE INDEX uq_iet_email_active
    ON public.index_expression_test USING btree (lower((email)::text))
    WHERE deleted_at IS NULL;